### ISSUE TITLE
Server Information by .conf upload (battle/client/drops/exp/misc/skill/player)

### ISSUE THREAD

**Issue by MitsuneBewbs** [marky291/ragnaranks#25]
**battle.conf** https://github.com/rathena/rathena/blob/master/conf/battle/battle.conf
arrow_decrement: 1

**client.conf** https://github.com/rathena/rathena/blob/master/conf/battle/client.conf
max_lv: 99

**drops.conf** https://github.com/rathena/rathena/blob/master/conf/battle/drops.conf
item_rate_common: 100
item_rate_common_boss: 100
item_rate_common_mvp: 100
item_rate_heal: 100
item_rate_heal_boss: 100
item_rate_heal_mvp: 100
item_rate_use: 100
item_rate_use_boss: 100
item_rate_use_mvp: 100
item_rate_equip: 100
item_rate_equip_boss: 100
item_rate_equip_mvp: 100
item_rate_card: 100
item_rate_card_boss: 100
item_rate_card_mvp: 100
item_rate_mvp: 100
item_rate_adddrop: 100
item_rate_treasure: 100

**exp.conf** https://github.com/rathena/rathena/blob/master/conf/battle/exp.conf
base_exp_rate: 100
job_exp_rate: 100

**misc.conf** https://github.com/rathena/rathena/blob/master/conf/battle/misc.conf
pk_mode: 0
pk_min_level: 55

**skill.conf** https://github.com/rathena/rathena/blob/master/conf/battle/skill.conf
delay_rate: 100
castrate_dex_scale: 150
vcast_stat_scale: 530

**player.conf** https://github.com/rathena/rathena/blob/master/conf/battle/player.conf
max_aspd: 190
max_third_aspd: 193
max_extended_aspd: 193

**Comment by marky291** [comment]
To be added as configs for listings?

**Comment by MitsuneBewbs** [comment]
> To be added as configs for listings?

Yep! I may not have them all in there though-- But I figured in the future if you wanted to implement .conf upload, these should be the important lines to pull from.

**Comment by marky291** [comment]
item rate -> item drop x

**Comment by marky291** [comment]
<img width="565" alt="Screenshot 2019-05-28 at 18 02 46" src="https://user-images.githubusercontent.com/5384515/58497014-ed5c1300-8172-11e9-87f7-1d89a523da91.png">

<img width="1030" alt="Screenshot 2019-05-28 at 18 03 30" src="https://user-images.githubusercontent.com/5384515/58497022-f0570380-8172-11e9-8612-7166af76d2ea.png">

**Comment by marky291** [comment]
May need a few days of usage before determining if configuration now suits better.
