### ISSUE TITLE
Copyright for Ragnarok Online elements that will appear on website

### ISSUE THREAD

**Issue by MitsuneBewbs** [marky291/ragnaranks#33]
> © Gravity Co., Ltd. & Lee MyoungJin (studio DTDS). All rights reserved. 
> © GungHo Online Entertainment, Inc. All Rights Reserved. 
> Reuse (re-reproduction, distribution, etc.) of this content is prohibited.

iRO website doesnt have anything about copyrights, kRO might but it wont translate. The only one that did is jRO, and jRO is where most if not all of my favorite anime arts used are from. So if we gotta cover more bases, I guess we could plug this somewhere in the footer.

**Comment by marky291** [comment]
There is no terms and conditions to usage of their materials, copyright footers will not make a difference these copyrights are usually required as some want credit for their work.


Not sure if its the case here.

**Comment by MitsuneBewbs** [comment]
Hey if that's the case-- Case closed lol.
I'm sure we'll be in more hot water later on because were advertising private servers GG. (Or not, look at how long RMS has been around yeesh.)

**Comment by marky291** [comment]
there is a little hole around that, im not responsible for what others post. :)
