### ISSUE TITLE
Missing Search option in 'Rates' -> Super High Rate

### ISSUE THREAD

**Issue by MitsuneBewbs** [marky291/ragnaranks#34]

**Comment by marky291** [comment]
![image](https://user-images.githubusercontent.com/5384515/58521310-2cf71f00-81b4-11e9-8f42-294104b9bc22.png)

![image](https://user-images.githubusercontent.com/5384515/58521312-2f597900-81b4-11e9-9ecc-b3f66fb8bb38.png)


![image](https://user-images.githubusercontent.com/5384515/58521313-308aa600-81b4-11e9-8f84-02ee8c2fdaf3.png)

**Comment by marky291** [comment]
@MitsuneBewbs these might need be checked, what is a low rate rates.. official (1x-5x) etc.

**Comment by MitsuneBewbs** [comment]
Official: 0x OR 0x-25x
Low: 50x or lower
Mid: 50x-300x
High: 300x-5,000k
Super: 5,000k+
Instant: ? Bugged.

**Comment by marky291** [comment]
Thank you, there was some naming issues hence it wasnt working. 💯
