### ISSUE TITLE
Default profile sliders

### ISSUE THREAD

**Issue by marky291** [marky291/ragnaranks#40]
Fun slides that relate to our branding as a filler. <3

<img width="882" alt="Screenshot 2019-05-26 at 23 52 22" src="https://user-images.githubusercontent.com/5384515/58388062-66dbf000-8011-11e9-8c0f-887cfe5c373e.png">

**Comment by marky291** [comment]
http://ragnaranks.com/listing/create

**Comment by MitsuneBewbs** [comment]
![ss-1](https://user-images.githubusercontent.com/50927576/58435838-ca9d0200-807f-11e9-9998-a0aa933f0078.png)
![ss-2](https://user-images.githubusercontent.com/50927576/58435839-ca9d0200-807f-11e9-90ff-30a40fd0e361.png)
![ss-3](https://user-images.githubusercontent.com/50927576/58435840-ca9d0200-807f-11e9-8769-fc677a90760a.png)
