### ISSUE TITLE
Users can have roles

### ISSUE THREAD

**Issue by marky291** [marky291/ragnaranks#41]
Roles and permissions can be granted or giving to users.

admin, moderator, member, creator, player

**Comment by marky291** [comment]
@MitsuneBewbs these roles make sense?

**Comment by marky291** [comment]
blocks #42

**Comment by MitsuneBewbs** [comment]
Absolutely makes sense! Love that.

**Comment by marky291** [comment]
https://github.com/spatie/laravel-permission#defining-a-super-admin

**Comment by marky291** [comment]
<img width="944" alt="Screenshot 2019-06-02 at 11 17 03" src="https://user-images.githubusercontent.com/5384515/58759813-f872c280-8527-11e9-8290-1df18d1f931a.png">

**Comment by marky291** [comment]
https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role

**Comment by marky291** [comment]
https://github.com/marky291/ragnaranks/wiki/Roles-&-Permissions
