### ISSUE TITLE
Card accents

### ISSUE THREAD

**Issue by marky291** [marky291/ragnaranks#44]
Cards accents require a database implementation, these accents allow cards to have a selection of preset colors.

**Comment by MitsuneBewbs** [comment]
Poring
![image](https://user-images.githubusercontent.com/50927576/58436185-506d7d00-8081-11e9-9ca8-a447646cf063.png)
FFC1CB
FFBCC6
FFB8C3
FFACB7
FFA4B0

**Comment by MitsuneBewbs** [comment]
Deviling // Tested with white font, fits better.
![image](https://user-images.githubusercontent.com/50927576/58436421-85c69a80-8082-11e9-8062-c9272da45221.png)
C3B1E3
AF9AD1
9176B9
8165A8
7A5AA4

**Comment by MitsuneBewbs** [comment]
Ghostring // Tested with white font, it's still pretty light but I chose darker fitting colors from the mob.
![image](https://user-images.githubusercontent.com/50927576/58436584-506e7c80-8083-11e9-9f59-df6cda1a2b8a.png)
CAD0EB
C3CBE8
BEC6E5
B8C1E3
B4BDE0

**Comment by MitsuneBewbs** [comment]
Drops // Tested with white font, not too light on the yellow.
![image](https://user-images.githubusercontent.com/50927576/58436905-d0e1ad00-8084-11e9-84d1-13798bc32a75.png)
FDD194
FFC989
FFC28B
FFBB7E
FFB47D

**Comment by MitsuneBewbs** [comment]
Poporing // Tested with white font, darker gradient.
![image](https://user-images.githubusercontent.com/50927576/58437103-a5ab8d80-8085-11e9-9c6d-974fbbe2ee92.png)
B6D987
A5D074
9BC16C
96BC69
719A4E

**Comment by MitsuneBewbs** [comment]
Pouring // Tested with white font.
![image](https://user-images.githubusercontent.com/50927576/58437531-9d545200-8087-11e9-9017-106cc953aa57.png)
A4DFFF
8CD3FF
6CC0FF
56B2FF
499DFF

**Comment by MitsuneBewbs** [comment]
Magmaring // White font friendly.
![image](https://user-images.githubusercontent.com/50927576/58437725-7d715e00-8088-11e9-8d3f-c0c0a4bbda0a.png)
FFBC4F
FCB64A
F7AA45
F59F3B
F29938

**Comment by marky291** [comment]
Thanks @MitsuneBewbs
