### ISSUE TITLE
Registration & My server after login

### ISSUE THREAD

**Issue by nakedwolf9** [marky291/ragnaranks#66]
after registration docent gets me back to home page as logged in, After logging in when i click on my server's it docent show any thing its empty hope it had a option that shows add create new server button if i dint have any server.

**Comment by marky291** [comment]
<img width="956" alt="Screenshot 2019-05-30 at 20 45 38" src="https://user-images.githubusercontent.com/5384515/58659854-ecb2b080-831b-11e9-893c-5c55392b0ef9.png">

**Comment by marky291** [comment]
possibly mail server
