### ISSUE TITLE
Add Tag: Instant Level

### ISSUE THREAD

**Issue by marky291** [marky291/ragnaranks#74]
https://github.com/marky291/ragnaranks/blob/master/database/migrations/2018_09_16_101736_create_server_table.php

**Comment by marky291** [comment]
get to it lmao

**Comment by MitsuneBewbs** [comment]
So I did do this, but it's not reflecting on front end. Not sure what's up with that lol.

**Comment by marky291** [comment]
That’s a migration file for database.

Read Laravel docs haha.

Php artisan migrate:fresh in phpstorm terminal

**Comment by MitsuneBewbs** [comment]
I did that but it's still not reflecting lol

**Comment by marky291** [comment]
@MitsuneBewbs your changes  + migrate:fresh worked for me. thank you 🥇
