### ISSUE TITLE
Create listing @Commands

### ISSUE THREAD

**Issue by marky291** [marky291/ragnaranks#80]

**Comment by marky291** [comment]
warp: true
		go: true
		autoloot: true
		alootid: true
		time: true
		storage: true
		allskill: true
		iteminfo: true
		jailtime: true
		hominfo: true
		feelreset: true
		duel: true
		request: true
		invite: true
		leave: true
		accept: true
		jump: true
		autotrade: true
		mobinfo: true
		whodrops: true
		whereis: true
		changegm: true
		refresh: true
		guildstorage: true
		who: true
		whogm: true
		afk: true

**Comment by nakedwolf9** [comment]
basic required:
commands
warp
go
storage
autoloot
alootid
jump
stoarge
duel
whodrops
mobinfo
whereis
iteminfo
rates
refresh
who
whogm
changegm
afk
guildstorage
autotrade
item
blvl
jlvl
allskill
homoinfo

**Comment by MitsuneBewbs** [comment]
showexp
rates
exp
autobuy
whosell
whobuy
joinbg
leavebg
reportafk
listenbg
listenwoe

**Comment by MitsuneBewbs** [comment]
I would request Commands section have the hover tooltip just like Configs.
![image](https://user-images.githubusercontent.com/50927576/58664022-0556a280-82eb-11e9-8a36-e752504ce62e.png)
I can edit the descriptions in those, so use a placeholder. [:

**Comment by marky291** [comment]
> I would request Commands section have the hover tooltip just like Configs.
> ![image](https://user-images.githubusercontent.com/50927576/58664022-0556a280-82eb-11e9-8a36-e752504ce62e.png)
> I can edit the descriptions in those, so use a placeholder. [:

https://github.com/marky291/ragnaranks/blob/master/resources/lang/en/configs.php

**Comment by MitsuneBewbs** [comment]
> > I would request Commands section have the hover tooltip just like Configs.
> > ![image](https://user-images.githubusercontent.com/50927576/58664022-0556a280-82eb-11e9-8a36-e752504ce62e.png)
> > I can edit the descriptions in those, so use a placeholder. [:
> 
> https://github.com/marky291/ragnaranks/blob/master/resources/lang/en/configs.php

So I did update that, BUT I meant do the same thing (tool tip on hover) for the command section on the right.
![image](https://user-images.githubusercontent.com/50927576/58670561-be71a880-82fc-11e9-9395-bd15432c1c87.png)
