### ISSUE TITLE
Descriptions needed for review ratings

### ISSUE THREAD

**Issue by marky291** [marky291/ragnaranks#9]
Each element that can be rating upon requires better descriptions.

<img width="719" alt="Screenshot 2019-05-15 at 20 38 03" src="https://user-images.githubusercontent.com/5384515/57803918-68740100-7751-11e9-8519-54f7e09e346d.png">

**Comment by MitsuneBewbs** [comment]
*Clarification needed:* Are all of these elements going to have 'x Experience'?
For example Donation Experience could translate to "ease of donation" like how easy the process was versus if the donation items are actually OP. The latter being something that might interest users over the ease of donating.

**Comment by marky291** [comment]
Anything that sounds good 🥇

**Comment by marky291** [comment]
Code for that is here: https://github.com/marky291/ragnaranks/blob/master/resources/views/listing/show.blade.php
